from django.conf.urls.defaults import *
from django.contrib import admin
from apps.disciplineform.views import *
from apps.datadashboard.views import *

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    (r'^$', 'apps.datadashboard.views.index'),
    (r'^media/(?P<path>.*)$',  'django.views.static.serve', {'document_root': 'media'}),
    (r'^favicon\.ico$', 'django.views.generic.simple.redirect_to', {'url': '/static/images/favicon.ico'}),
    (r'^admin/doc/', include('django.contrib.admindocs.urls')),
    (r'^admin/(.*)', admin.site.root),
    #(r'^boe/$', boe_vacancy_form),
    (r'^discipline/$', discipline_home),
    (r'^discipline/login/$', discipline_login),
    (r'^discipline/login_submit/$', discipline_login_submit),
    (r'^discipline/enter_incident/$', enter_incident),
    (r'^discipline/add_disciplinary_action/(.+)/$', add_disciplinary_action),
    (r'^discipline/edit_disciplinary_action/(.+)/$', edit_disciplinary_action),
    (r'^discipline/edit_incident/(.+)/$', edit_incident),
    (r'^discipline/edit_action/(.+)/$', edit_action),
    (r'^discipline/students_for_incident/(.+)/$', view_students_for_incident),
    (r'^discipline/incident_detail/(.+)/$', incident_detail),
    (r'^discipline/discipline_summary/$',discipline_summary),
    (r'^discipline/view_incidents_student/$', view_incidents_student_post),
    (r'^discipline/view_incidents_student/(.+)/$', view_incidents_student),
    (r'^discipline/view_incidents_date/$', view_incidents_date_post),
    (r'^discipline/view_incidents_date/(.+)/$', view_incidents_date),
    (r'^discipline/view_incidents_referrer/$', view_incidents_referrer_post),
    (r'^discipline/view_incidents_referrer/(.+)/$', view_incidents_referrer),
    (r'^discipline/view_incidents_location/$', view_incidents_location),
    (r'^discipline/view_incidents_location/(.+)/$', view_incidents_location),
    (r'^discipline/view_incidents_problem_behaviors_minor/(.+)/$', view_incidents_problem_behaviors_minor),
    (r'^discipline/view_incidents_problem_behaviors_major/(.+)/$', view_incidents_problem_behaviors_major),
    (r'^discipline/incidents_by_student/$', incidents_by_student),
    (r'^discipline/incidents_by_referrer/$', incidents_by_referrer),
    (r'^discipline/incidents_by_location/$', incidents_by_location),
    (r'^discipline/incidents_by_grade/$', incidents_by_grade),
    (r'^discipline/incidents_by_month/$', incidents_by_month),
    (r'^discipline/incidents_by_day_of_week/$', incidents_by_day_of_week),
    (r'^discipline/incidents_by_time/$', incidents_by_time),
    (r'^discipline/rules_broken/$', rules_broken),
    (r'^discipline/major_problem_behaviors/$', major_problem_behaviors),
    (r'^discipline/minor_problem_behaviors/$', minor_problem_behaviors),
    (r'^discipline/in_school_suspensions/$', in_school_suspensions),
    (r'^discipline/out_school_suspensions/$', out_school_suspensions),
    (r'^discipline/out_school_suspensions_specialed/$', out_school_suspensions_specialed),
    (r'^discipline/in_school_suspensions_specialed/$', in_school_suspensions_specialed),
    (r'^discipline/suspensions_specialed/$', suspensions_specialed),
    (r'^discipline/referral_view/(.+)/$', referral_view),
    (r'^discipline/generate_srm_xml/$', generate_srm_xml),
    (r'^discipline/generate_check_csv/$', generate_check_csv),
    (r'^discipline/validation_summary/$', validation_summary),
    (r'^discipline/show_incidents_no_actions/$', show_incidents_no_actions),
    (r'^discipline/show_actions_no_incidents/$', show_actions_no_incidents),
    (r'^discipline/show_students_nonstandard_names/$', show_students_nonstandard_names),
    (r'^discipline/change_school_year/$', change_school_year),
    (r'^discipline/pyramid_view/$', pyramid_view),
)